import Head from 'next/head'
import Desktop from '../components/Desktop'

const Home = () => {
  return (
    <div>
      <Head>
        <title>Os App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Desktop/>
    </div>
  )
}

export default Home