export const UIactionTypes = {
    CHANGE_THEME: "CHANGE_THEME",
    THEME_WAS_CHANGED: "THEME_WAS_CHANGED",
    OPEN_SEARCH_MODAL: "OPEN_SEARCH_MODAL",
    CLOSE_SEARCH_MODAL:"CLOSE_SEARCH_MODAL",
};